var selectedArtists = [];

$('select').innerHTML += '<small id="amaranthe" class="artists" onclick = toggleArtist()>amaranthe</small><br>'
$('select').innerHTML += '<small id="junny" class="artists" onclick = toggleArtist()>junny</small><br>'
$('select').innerHTML += '<small id="jhene" class="artists" onclick = toggleArtist()>jhene</small><br>'
$('select').innerHTML += '<small id="newJeans" class="artists" onclick = toggleArtist()>new jeans</small><br>'
$('select').innerHTML += '<small id="aespa" class="artists" onclick = toggleArtist()>aespa</small><br>'
$('select').innerHTML += '<small id="rose" class="artists" onclick = toggleArtist()>rose</small><br>'
$('select').innerHTML += '<small id="stayc" class="artists" onclick = toggleArtist()>stayc</small><br>'
$('select').innerHTML += '<small id="taeyeon" class="artists" onclick = toggleArtist()>taeyeon</small><br>'
$('select').innerHTML += '<small id="ghost" class="artists" onclick = toggleArtist()>ghost</small><br>'

songs = {};
songs.amaranthe = {};
songs.junny = {};
songs.jhene = {};
songs.newJeans = {};
songs.aespa = {};
songs.rose = {};
songs.stayc = {};
songs.taeyeon = {};
songs.ghost = {};

songs.amaranthe["razorblade"] = "B https://www.youtube.com/watch?v=HkDw179I2-4";
songs.amaranthe["call out my name"] = "B https://www.youtube.com/watch?v=23AlXnruNPk";
songs.amaranthe["unified"] = "B https://www.youtube.com/watch?v=fhwYvAv4GMw";
songs.amaranthe["directors cut"] = "B https://www.youtube.com/watch?v=-tjOISbsZck";
songs.amaranthe["one million light years away"] = "B https://www.youtube.com/watch?v=6DbAruY9z-w";
songs.amaranthe["serendipity"] = "B https://www.youtube.com/watch?v=CJuJ1oJmGxQ";
songs.amaranthe["rain"] = "BC https://www.youtube.com/watch?v=5EDmp7RbIP0";
songs.amaranthe["skyline"] = "BC https://www.youtube.com/watch?v=-NRthBF9Kd0";
songs.amaranthe["exhale"] = "BC https://www.youtube.com/watch?v=jAvmKdaavnc";
songs.amaranthe["21"] = "BC https://www.youtube.com/watch?v=WKWVG4c47No";
songs.amaranthe["supersonic"] = "BC https://www.youtube.com/watch?v=XnxrxP2P8_Y";
songs.amaranthe["electroheart"] = "C";
songs.amaranthe["momentum"] = "BC https://www.youtube.com/watch?v=1GVBkIhdwsM";
songs.amaranthe["endlessly"] = "B https://www.youtube.com/watch?v=w7VddOG8vM0";
songs.amaranthe["maximize"] = "BC https://www.youtube.com/watch?v=nfk7YZJtmeo";
songs.amaranthe["hunger"] = "BC https://www.youtube.com/watch?v=9y25snz83ms";
songs.amaranthe["amaranthine"] = "BC https://www.youtube.com/watch?v=D8lV1To-_fU";
songs.amaranthe["splinter in my soul"] = "C";
songs.amaranthe["enter the maze"] = "C";
songs.amaranthe["breaking point"] = "C";
songs.amaranthe["my transition"] = "C";
songs.amaranthe["automatic"] = "C";
songs.amaranthe["act of desperation"] = "C";
songs.amaranthe["afterlife"] = "C";
songs.amaranthe["the nexus"] = "C";
songs.amaranthe["theory of everything"] = "C";
songs.amaranthe["stardust"] = "C";
songs.amaranthe["burn with me"] = "C";
songs.amaranthe["mechanical illusion"] = "C";
songs.amaranthe["future on hold"] = "C";
songs.amaranthe["transhuman"] = "C";
songs.amaranthe["infinity"] = "C";
songs.amaranthe["dynamite"] = "C";
songs.amaranthe["drop dead cynical"] = "C";
songs.amaranthe["boom"] = "C";
songs.amaranthe["dream"] = "C";
songs.amaranthe["gg6"] = "C";
songs.amaranthe["breakthrough starshot"] = "C";
songs.amaranthe["my haven"] = "C";
songs.amaranthe["iconic"] = "C";
songs.amaranthe["say the word"] = "C";
songs.amaranthe["fearless"] = "C";
songs.amaranthe["make it better"] = "C";
songs.amaranthe["scream my name"] = "C";
songs.amaranthe["adrenaline"] = "C";
songs.amaranthe["strong"] = "C";
songs.amaranthe["theGame"] = "C";
songs.amaranthe["crystalline"] = "C";
songs.amaranthe["boomerang"] = "C";
songs.amaranthe["on the rocks"] = "C";
songs.amaranthe["limitless"] = "C";
songs.amaranthe["faster"] = "C";
songs.amaranthe["trinity"] = "C";
songs.amaranthe["massive addictive"] = "C";
songs.amaranthe["digital world"] = "C";
songs.amaranthe["true"] = "C";
songs.amaranthe["unreal"] = "C";
songs.amaranthe["over and done"] = "C";
songs.amaranthe["danger zone"] = "C";
songs.amaranthe["an ordinary abnormality"] = "C";
songs.amaranthe["that song"] = "C";
songs.amaranthe["fury"] = "C";
songs.amaranthe["break down and cry"] = "C";
songs.amaranthe["fireball"] = "C";
songs.amaranthe["the score"] = "C";
songs.amaranthe["365"]= "C";
songs.amaranthe["inferno"] = "C";
songs.amaranthe["countdown"] = "C";
songs.amaranthe["helix"] = "C";
songs.amaranthe["die and wake up"] = "C";
songs.amaranthe["do or die"] = "C";
songs.amaranthe["the catalyst"] = "C";
songs.amaranthe["insatiable"] = "C";
songs.amaranthe["damnation flame"] = "C";
songs.amaranthe["liberated"] = "C";
songs.amaranthe["revision"] = "C";
songs.amaranthe["interference"] = "C";
songs.amaranthe["stay a little while"] = "C";
songs.amaranthe["ecstasy"] = "C";
songs.amaranthe["breaking the waves"] = "C";
songs.amaranthe["outer dimensions"] = "C";
songs.amaranthe["resistance"] = "C";
songs.amaranthe["find life"] = "C";
songs.amaranthe["pvp"] = "C";
songs.amaranthe["make it better"] = "C";
songs.amaranthe["viral"] = "C";

songs.junny["bona fide"] = "BC https://www.youtube.com/watch?v=MNM_x2AqEBc";
songs.junny["levitate"] = "BC https://www.youtube.com/watch?v=8Zte8fpn12c";
songs.junny["mono"] = "BC https://www.youtube.com/watch?v=ZACnULmpVXg";
songs.junny["stay under"] = "BC https://www.youtube.com/watch?v=LVtx0TlDwnQ";
songs.junny["movie"] = "BC https://www.youtube.com/watch?v=_P9ty76m5FU";
songs.junny["menu"] = "BC https://www.youtube.com/watch?v=SusJkVuOvl4";
songs.junny["mercury"] = "C";
songs.junny["not about you"] = "C";
songs.junny["mugshot"] = "C";
songs.junny["just a number"] = "C";
songs.junny["oh!!"] = "C";
songs.junny["obvious"] = "C";
songs.junny["color me"] = "C";
songs.junny["get ya"] = "C";
songs.junny["boyhood"] = "C";
songs.junny["rush"] = "C";
songs.junny["taste"] = "C";
songs.junny["daylight"] = "C";
songs.junny["here we go again"] = "C";
songs.junny["complications"] = "C";
songs.junny["figure8"] = "C";
songs.junny["distance"] = "C";
songs.junny["say"] = "C";
songs.junny["waste your time"] = "C";
songs.junny["trust"] = "C";
songs.junny["be mine"] = "C";
songs.junny["living dream"] = "C";
songs.junny["feel that"] = "C";
songs.junny["patience"] = "C";
songs.junny["zone"] = "C";
songs.junny["for the weekend"] = "C";
songs.junny["blind game"] = "C";
songs.junny["wywf"] = "C";
songs.junny["handle you"] = "C";
songs.junny["down under"] = "C";
songs.junny["choose"] = "C";
songs.junny["rise and fall"] = "C";
songs.junny["wine"] = "C";
songs.junny["switch"] = "C";
songs.junny["bed"] = "C";
songs.junny["success"] = "C";
songs.junny["winter"] = "C";
songs.junny["window"] = "C";
songs.junny["21"] = "C";
songs.junny["trilla"] = "C";
songs.junny["age"] = "C";
songs.junny["up all night"] = "C";
songs.junny["spoiler"] = "C";
songs.junny["years"] = "C";
songs.junny["getaway"] = "C";
songs.junny["untitled"] = "C";
songs.junny["feel"] = "C";
songs.junny["maybe"] = "C";
songs.junny["aura"] = "C";
songs.junny["by my side"] = "C";
songs.junny["new girl"] = "C";
songs.junny["sober"] = "C";
songs.junny["inside"] = "C";
songs.junny["hide and sick"] = "C";
songs.junny["darling"] = "C";
songs.junny["optimist"] = "C";
songs.junny["invitation"] = "C";

songs.jhene["brave"] = "BC https://www.youtube.com/watch?v=0paO14gvFAk";
songs.jhene["jukai"] = "BC https://www.youtube.com/watch?v=-Vowb5dcQmw";
songs.jhene["lsd"] = "BC https://www.youtube.com/watch?v=PtiXC4YLUmU";
songs.jhene["while were young"] = "BC https://www.youtube.com/watch?v=LjvwRSKVQNs";
songs.jhene["newer balance"] = "BC https://www.youtube.com/watch?v=AG3v9933ZIw";
songs.jhene["bad trip"] = "BC https://www.youtube.com/watch?v=2HYe8MtjEbI";
songs.jhene["trip"] = "BC https://www.youtube.com/watch?v=V_q8r9xt8PU";
songs.jhene["tryna smoke"] = "BC https://www.youtube.com/watch?v=-ov6tH8KSvY";
songs.jhene["born tired"] = "BC https://www.youtube.com/watch?v=kLTwNhHVc7Q";
songs.jhene["all good"] = "BC https://www.youtube.com/watch?v=8YmSeLRLYTE";
songs.jhene["mourning doves"] = "BC https://www.youtube.com/watch?v=CKxGuUkoSlU";
songs.jhene["limbo limbo limbo"] = "C";
songs.jhene["ways"] = "C";
songs.jhene["to love and die"] = "C";
songs.jhene["spotless mind"] = "C";
songs.jhene["its cool"] = "C";
songs.jhene["lyin king"] = "C";
songs.jhene["the pressure"] = "C";
songs.jhene["eternal sunshine"] = "C";
songs.jhene["promises"] = "C";
songs.jhene["remember"] = "C";
songs.jhene["pretty bird"] = "C";
songs.jhene["blue dream"] = "C";
songs.jhene["beautiful ruin"] = "C";
songs.jhene["moments"] = "C";
songs.jhene["olla"] = "C";
songs.jhene["when we love"] = "C";
songs.jhene["sativa"] = "C";
songs.jhene["new balance"] = "C";
songs.jhene["you are here"] = "C";
songs.jhene["never call me"] = "C";
songs.jhene["nobody"] = "C";
songs.jhene["lotus"] = "C";
songs.jhene["triggered"] = "C";
songs.jhene["overstimulated"] = "C";
songs.jhene["oblivion"] = "C";
songs.jhene["psilocybin"] = "C";
songs.jhene["mystic journey"] = "C";
songs.jhene["picture perfect"] = "C";
songs.jhene["sing to me"] = "C";
songs.jhene["frequency"] = "C";
songs.jhene["ascension"] = "C";
songs.jhene["hello ego"] = "C";
songs.jhene["clear my mind"] = "C";
songs.jhene["none of your concern"] = "C";
songs.jhene["speak"] = "C";
songs.jhene["bs"] = "C";
songs.jhene["pussy fairy"] = "C";
songs.jhene["hoe"] = "C";
songs.jhene["one way"] = "C";
songs.jhene["define me"] = "C";
songs.jhene["surrender"] = "C";
songs.jhene["love"] = "C";
songs.jhene["10k hours"] = "C";
songs.jhene["summer 2020"] = "C";
songs.jhene["pray for you"] = "C";
songs.jhene["lightning and thunder"] = "C";
songs.jhene["magic hour"] = "C";
songs.jhene["party for me"] = "C";
songs.jhene["a and B"] = "C";
songs.jhene["come on"] = "C";
songs.jhene["on the way"] = "C";
songs.jhene["down again"] = "C";
songs.jhene["wading"] = "C";

songs.newJeans["attention"] = "BC https://www.youtube.com/watch?v=js1CtxSY38I";
songs.newJeans["omg"] = "BC https://www.youtube.com/watch?v=sVTy_wmn5SU";
songs.newJeans["hype boy"] = "C";
songs.newJeans["cookie"] = "C";
songs.newJeans["hurt"] = "C";
songs.newJeans["new jeans"] = "C";
songs.newJeans["super shy"] = "C";
songs.newJeans["eta"] = "C";
songs.newJeans["cool with you"] = "C";
songs.newJeans["get up"] = "C";
songs.newJeans["asap"] = "C";
songs.newJeans["ditto"] = "C";
songs.newJeans["how sweet"] = "C";
songs.newJeans["bubble gum"] = "C";
songs.newJeans["supernatural"] = "C";
songs.newJeans["right now"] = "C";

songs.aespa["sun and moon"] = "B https://www.youtube.com/watch?v=PLsEfyfJFbo";
songs.aespa["just another girl"] = "B https://www.youtube.com/watch?v=hZP4khXrMgE";
songs.aespa["hold on tight"] = "B https://www.youtube.com/watch?v=1XZRhrt1Tkg";
songs.aespa["armageddon"] = "BC https://www.youtube.com/watch?v=nFYwcndNuOY";
songs.aespa["live my life"] = "BC https://www.youtube.com/watch?v=YEA1ROHi0Eg";
songs.aespa["prologue"] = "BC https://www.youtube.com/watch?v=P8Zd56wknlk";
songs.aespa["iconic"] = "BC https://www.youtube.com/watch?v=gj-lvvYQdiU";
songs.aespa["lucid dream"] = "BC https://www.youtube.com/watch?v=5DhAts7WcPk";
songs.aespa["aenergy"] = "C";
songs.aespa["better things"] = "C";
songs.aespa["black mamba"] = "C";
songs.aespa["die trying"] = "C";
songs.aespa["drama"] = "C";
songs.aespa["dont blink"] = "C";
songs.aespa["dreams come true"] = "C";
songs.aespa["flights not feelings"] = "C";
songs.aespa["flowers"] = "C";
songs.aespa["forever"] = "C";
songs.aespa["get goin"] = "C";
songs.aespa["girls"] = "C";
songs.aespa["hot air balloon"] = "C";
songs.aespa["hot mess"] = "C";
songs.aespa["illusion"] = "C";
songs.aespa["ill make you cry"] = "C";
songs.aespa["im unhappy"] = "C";
songs.aespa["jingle bell rock"] = "C";
songs.aespa["kill it"] = "C";
songs.aespa["licorice"] = "C";
songs.aespa["lifes too short"] = "C";
songs.aespa["lingo"] = "C";
songs.aespa["long chat"] = "C";
songs.aespa["melody"] = "C";
songs.aespa["mine"] = "C";
songs.aespa["we go"] = "C";
songs.aespa["next level"] = "C";
songs.aespa["pink hoodie"] = "C";
songs.aespa["regret of the times"] = "C";
songs.aespa["salty and sweet"] = "C";
songs.aespa["savage"] = "C";
songs.aespa["set the tone"] = "C";
songs.aespa["spicy"] = "C";
songs.aespa["supernova"] = "C";
songs.aespa["til we meet again"] = "C";
songs.aespa["thirsty"] = "C";
songs.aespa["trick or trick"] = "C";
songs.aespa["welcome to my world"] = "C";
songs.aespa["bahama"] = "C";
songs.aespa["whiplash"] = "C";
songs.aespa["yeppi yeppi"] = "C";
songs.aespa["yolo"] = "C";
songs.aespa["you"] = "C";
songs.aespa["zoom zoom"] = "C";
songs.aespa["ICU"] = "C";

songs.rose["call it the end"] = "A https://www.youtube.com/watch?v=nOo3a2tT1LQ";
songs.rose["too bad for us"] = "AB https://www.youtube.com/watch?v=FQmgNCStzQM";
songs.rose["drinks or coffee"] = "B https://www.youtube.com/watch?v=PFDO5OZO61Y";
songs.rose["two years"] = "B https://www.youtube.com/watch?v=lktucPDH5IY";
songs.rose["number one girl"] = "B https://www.youtube.com/watch?v=pZ1NdE69VTs";
songs.rose["stay a little longer"] = "BC https://www.youtube.com/watch?v=vHvOYQ0hbBA";
songs.rose["toxic till the end"] = "BC https://www.youtube.com/watch?v=eA0lHNZ1KCA";
songs.rose["3am"] = "C";
songs.rose["dance all night"] = "C";
songs.rose["gameboy"] = "C";
songs.rose["not the same"] = "C";
songs.rose["APT"] = "C";


songs.stayc["ill be there"] = "A https://www.youtube.com/watch?v=OD2k86rKRI4";
songs.stayc["so bad"] = "AB https://www.youtube.com/watch?v=lcRV2gyEfMo";
songs.stayc["meow"] = "AB https://www.youtube.com/watch?v=b8yjHGQ4hA4";
songs.stayc["beautiful monster"] = "B https://www.youtube.com/watch?v=juQvizeZJFM";
songs.stayc["young luv"] = "BC https://www.youtube.com/watch?v=J8VHA8HeK4Q";
songs.stayc["gummy bear"] = "BC https://www.youtube.com/watch?v=yyFyEsdRlEY";
songs.stayc["meant to be"] = "BC https://www.youtube.com/watch?v=Zszb7LQ3T6Q";
songs.stayc["twenty"] = "C";
songs.stayc["give it 2 me"] = "C";
songs.stayc["let me know"] = "C";
songs.stayc["roses"] = "C";
songs.stayc["beauty bomb"] = "C";
songs.stayc["stay with me"] = "C";
songs.stayc["flexing on my ex"] = "C";
songs.stayc["slow down"] = "C";
songs.stayc["complex"] = "C";
songs.stayc["247"] = "C";
songs.stayc["cheeky icy thang"] = "C";
songs.stayc["1 thing"] = "C";
songs.stayc["find"] = "C";
songs.stayc["nada"] = "C";
songs.stayc["troublemaker"] = "C";
songs.stayc["stereotype"] = "C";
songs.stayc["run2u"] = "C";
songs.stayc["same same"] = "C";
songs.stayc["not like you"] = "C";
songs.stayc["be mine"] = "C";
songs.stayc["butterfly"] = "C";
songs.stayc["i want u baby"] = "C";
songs.stayc["bubble"] = "C";
songs.stayc["i wanna do"] = "C";
songs.stayc["asap"] = "C";
songs.stayc["so what"] = "C";
songs.stayc["i like it"] = "C";
songs.stayc["run2utak"] = "C";
songs.stayc["teddy bear"] = "C";
songs.stayc["like this"] = "C";
songs.stayc["love fool"] = "C";
songs.stayc["love"] = "C";
songs.stayc["poppy"] = "C";
songs.stayc["lit"] = "C";
songs.stayc["star"] = "C";
songs.stayc["tell me now"] = "C";
songs.stayc["fakin"] = "C";
songs.stayc["gpt"] = "C";

songs.taeyeon["siren"] = "AB https://www.youtube.com/watch?v=kci45V8zPx8";
songs.taeyeon["cant control myself"] = "AB https://www.youtube.com/watch?v=RccDIpx4ZMM";
songs.taeyeon["toddler"] = "AB https://www.youtube.com/watch?v=EaIb4RzAvEI";
songs.taeyeon["no love again"] = "B https://www.youtube.com/watch?v=XaPZKYbmveQ";
songs.taeyeon["spark"] = "B https://www.youtube.com/watch?v=eP4ga_fNm-E";
songs.taeyeon["burn it down"] = "B https://www.youtube.com/watch?v=Bexk2HA3J-Y";
songs.taeyeon["some nights"] = "B https://www.youtube.com/watch?v=a7NoogZ2eFo";
songs.taeyeon["dear me"] = "B https://www.youtube.com/watch?v=bho0m505qVA";
songs.taeyeon["ending credits"] = "BC https://www.youtube.com/watch?v=DCtcLIS3yhw";
songs.taeyeon["you better not"] = "BC https://www.youtube.com/watch?v=t-0-i5vmtBo";
songs.taeyeon["stress"] = "BC https://www.youtube.com/watch?v=N2NLxGkr8kg";
songs.taeyeon["do you love me"] = "BC https://www.youtube.com/watch?v=d6CkeV4Hves";
songs.taeyeon["my tragedy"] = "BC https://www.youtube.com/watch?v=M02W--fl1js";
songs.taeyeon["here i am"] = "BC https://www.youtube.com/watch?v=q_rQmUVgCo0";
songs.taeyeon["find me"] = "BC https://www.youtube.com/watch?v=WU7SsAnDLKw";
songs.taeyeon["INVU"] = "C";
songs.taeyeon["all for nothing"] = "C";
songs.taeyeon["fabulous"] = "C";
songs.taeyeon["what do i call you"] = "C";
songs.taeyeon["heaven"] = "C";
songs.taeyeon["LOL"] = "C";
songs.taeyeon["to x"] = "C";
songs.taeyeon["blue"] = "C";
songs.taeyeon["baram x 3"] = "C";
songs.taeyeon["circus"] = "C";
songs.taeyeon["blue eyes"] = "C";
songs.taeyeon["strangers"] = "C";
songs.taeyeon["playlist"] = "C";
songs.taeyeon["wildfire"] = "C";
songs.taeyeon["better babe"] = "C";
songs.taeyeon["disaster"] = "C";
songs.taeyeon["cover up"] = "C";
songs.taeyeon["feel so fine"] = "C";
songs.taeyeon["im ok"] = "C";
songs.taeyeon["sweet love"] = "C";
songs.taeyeon["lonely night"] = "C";
songs.taeyeon["eraser"] = "C";
songs.taeyeon["curtain call"] = "C";
songs.taeyeon["11:11"] = "C";
songs.taeyeon["i"] = "C";
songs.taeyeon["blur"] = "C";
songs.taeyeon["why"] = "C";
songs.taeyeon["timeless"] = "C";
songs.taeyeon["gemini"] = "C";
songs.taeyeon["farewell"] = "C";
songs.taeyeon["fine"] = "C";
songs.taeyeon["time lapse"] = "C";
songs.taeyeon["set myself on fire"] = "C";
songs.taeyeon["hot mess"] = "C";
songs.taeyeon["four seasons"] = "C";
songs.taeyeon["U R"] = "C";
songs.taeyeon["letter to myself"] = "C";
songs.taeyeon["starlight"] = "C";
songs.taeyeon["good thing"] = "C";
songs.taeyeon["rain"] = "C";
songs.taeyeon["make me love you"] = "C";
songs.taeyeon["time spent walking through memories"] = "C";
songs.taeyeon["weekend"] = "C";
songs.taeyeon["cold as hell"] = "C";
songs.taeyeon["happy"] = "C";
songs.taeyeon["fashion"] = "C";
songs.taeyeon["wine"] = "C";
songs.taeyeon["nightmare"] = "C";
songs.taeyeon["melt away"] = "C";
songs.taeyeon["heart"] = "C";
songs.taeyeon["drawing our moments"] = "C";
songs.taeyeon["something new"] = "C";
songs.taeyeon["all night long"] = "C";
songs.taeyeon["one day"] = "C";
songs.taeyeon["i got love"] = "C";
songs.taeyeon["when i was young"] = "C";
songs.taeyeon["one day"] = "C";
songs.taeyeon["i got love"] = "C";
songs.taeyeon["when i was young"] = "C";
songs.taeyeon["i blame on you"] = "C";
songs.taeyeon["love in color"] = "C";
songs.taeyeon["hands on me"] = "C";
songs.taeyeon["night"] = "C";
songs.taeyeon["city love"] = "C";
songs.taeyeon["love you like crazy"] = "C";
songs.taeyeon["gravity"] = "C";

songs.ghost["gravity"] = "C";
songs.ghost["gravity"] = "C";
songs.ghost["gravity"] = "C";
songs.ghost["gravity"] = "C";
songs.ghost["gravity"] = "C";
songs.ghost["gravity"] = "C";
songs.ghost["gravity"] = "C";
songs.ghost["gravity"] = "C";
songs.ghost["gravity"] = "C";
songs.ghost["gravity"] = "C";
songs.ghost["gravity"] = "C";
songs.ghost["gravity"] = "C";
songs.ghost["gravity"] = "C";
songs.ghost["gravity"] = "C";
songs.ghost["gravity"] = "C";
songs.ghost["gravity"] = "C";
songs.ghost["gravity"] = "C";
songs.ghost["gravity"] = "C";
songs.ghost["gravity"] = "C";
songs.ghost["gravity"] = "C";
songs.ghost["gravity"] = "C";
songs.ghost["gravity"] = "C";
songs.ghost["gravity"] = "C";
songs.ghost["gravity"] = "C";
songs.ghost["gravity"] = "C";
songs.ghost["gravity"] = "C";
songs.ghost["gravity"] = "C";
songs.ghost["gravity"] = "C";
songs.ghost["gravity"] = "C";
songs.ghost["gravity"] = "C";
songs.ghost["gravity"] = "C";
songs.ghost["gravity"] = "C";
songs.ghost["gravity"] = "C";
songs.ghost["gravity"] = "C";
songs.ghost["gravity"] = "C";
songs.ghost["gravity"] = "C";
songs.ghost["gravity"] = "C";
songs.ghost["gravity"] = "C";
songs.ghost["gravity"] = "C";
songs.ghost["gravity"] = "C";
songs.ghost["gravity"] = "C";
songs.ghost["gravity"] = "C";
songs.ghost["gravity"] = "C";
songs.ghost["gravity"] = "C";
songs.ghost["gravity"] = "C";
songs.ghost["gravity"] = "C";
songs.ghost["gravity"] = "C";
songs.ghost["gravity"] = "C";
songs.ghost["gravity"] = "C";
songs.ghost["gravity"] = "C";
songs.ghost["gravity"] = "C";
songs.ghost["gravity"] = "C";
songs.ghost["gravity"] = "C";
songs.ghost["gravity"] = "C";
songs.ghost["gravity"] = "C";









for (const [key, value] of Object.entries(songs.aespa)) {
  console.log(`${key}: ${value}`);
}


console.log(songs["amaranthe"]["365"]);

