var selectedArtists = [];
var havePlayedASong = false;
var needsUpdate = false;

console.log(location.hostname)

songs = {};
songs.amaranthe = {};
songs.junny = {};
songs.jhene = {};
songs.newJeans = {};
songs.aespa = {};
songs.rose = {};
songs.stayc = {};
songs.taeyeon = {};
songs.ghost = {};

songs.amaranthe["razorblade"] = "B https://www.youtube.com/watch?v=HkDw179I2-4";
songs.amaranthe["call out my name"] = "B https://www.youtube.com/watch?v=23AlXnruNPk";
songs.amaranthe["unified"] = "B https://www.youtube.com/watch?v=fhwYvAv4GMw";
songs.amaranthe["directors cut"] = "BC https://www.youtube.com/watch?v=-tjOISbsZck";
songs.amaranthe["one million light years away"] = "B https://www.youtube.com/watch?v=6DbAruY9z-w";
songs.amaranthe["serendipity"] = "B https://www.youtube.com/watch?v=CJuJ1oJmGxQ";
songs.amaranthe["rain"] = "BC https://www.youtube.com/watch?v=5EDmp7RbIP0";
songs.amaranthe["skyline"] = "BC https://www.youtube.com/watch?v=-NRthBF9Kd0";
songs.amaranthe["exhale"] = "BC https://www.youtube.com/watch?v=jAvmKdaavnc";
songs.amaranthe["21"] = "BC https://www.youtube.com/watch?v=WKWVG4c47No";
songs.amaranthe["supersonic"] = "BC https://www.youtube.com/watch?v=XnxrxP2P8_Y";
songs.amaranthe["electroheart"] = "C https://www.youtube.com/watch?v=BHx-WgqvBmc";
songs.amaranthe["momentum"] = "BC https://www.youtube.com/watch?v=1GVBkIhdwsM";
songs.amaranthe["endlessly"] = "B https://www.youtube.com/watch?v=w7VddOG8vM0";
songs.amaranthe["maximize"] = "C https://www.youtube.com/watch?v=nfk7YZJtmeo";
songs.amaranthe["hunger"] = "BC https://www.youtube.com/watch?v=9y25snz83ms";
songs.amaranthe["amaranthine"] = "BC https://www.youtube.com/watch?v=D8lV1To-_fU";
songs.amaranthe["splinter in my soul"] = "C https://www.youtube.com/watch?v=JHeeuvtRLsM";
songs.amaranthe["enter the maze"] = "BC https://www.youtube.com/watch?v=cIASbMwAHuI";
songs.amaranthe["breaking point"] = "BC https://www.youtube.com/watch?v=_s5PG4vn-HI";
songs.amaranthe["my transition"] = "BC https://www.youtube.com/watch?v=z6TxMiP9ITw";
songs.amaranthe["automatic"] = "BC https://www.youtube.com/watch?v=H0foIiSkSew";
songs.amaranthe["act of desperation"] = "C https://www.youtube.com/watch?v=Q7WesGjbHyM";
songs.amaranthe["afterlife"] = "C https://www.youtube.com/watch?v=B04hD_fCbuY";
songs.amaranthe["the nexus"] = "C https://www.youtube.com/watch?v=SxOybZcRXhI";
songs.amaranthe["theory of everything"] = "C https://www.youtube.com/watch?v=U2WBDbWzLjc";
songs.amaranthe["stardust"] = "C https://www.youtube.com/watch?v=18cv7mEDE5w";
songs.amaranthe["burn with me"] = "C https://www.youtube.com/watch?v=IEgkUKCwi30";
songs.amaranthe["mechanical illusion"] = "BC https://www.youtube.com/watch?v=sXsdKbIbJyA";
songs.amaranthe["future on hold"] = "C https://www.youtube.com/watch?v=G4Ry0A_7X4I";
songs.amaranthe["transhuman"] = "C https://www.youtube.com/watch?v=L_-pAcDpGQc";
songs.amaranthe["infinity"] = "C https://www.youtube.com/watch?v=OVrQ2sfP7QU";
songs.amaranthe["dynamite"] = "C https://www.youtube.com/watch?v=h7EY6SAcjvU";
songs.amaranthe["drop dead cynical"] = "C https://www.youtube.com/watch?v=RdyExxpd3Pg";
songs.amaranthe["boom"] = "C https://www.youtube.com/watch?v=wY0n31kWI8c";
songs.amaranthe["dream"] = "C https://www.youtube.com/watch?v=SefkaPqyidc";
songs.amaranthe["gg6"] = "C https://www.youtube.com/watch?v=rg8_r4SXuW0";
songs.amaranthe["breakthrough starshot"] = "C https://www.youtube.com/watch?v=ceCHums5uxk";
songs.amaranthe["my haven"] = "BC https://www.youtube.com/watch?v=IElqhXxPGkM";
songs.amaranthe["iconic"] = "C https://www.youtube.com/watch?v=--KAhR58HBg";
songs.amaranthe["say the word"] = "C https://www.youtube.com/watch?v=kvfLqc6vFHE";
songs.amaranthe["fearless"] = "C https://www.youtube.com/watch?v=JzPUBTR4L_4";
songs.amaranthe["make it better"] = "C https://www.youtube.com/watch?v=yHG9EQx3bko";
songs.amaranthe["scream my name"] = "C https://www.youtube.com/watch?v=MEm0NXEMBho";
songs.amaranthe["adrenaline"] = "C https://www.youtube.com/watch?v=irxjwfzFEHA";
songs.amaranthe["strong"] = "C https://www.youtube.com/watch?v=59Ny29nNh2A";
songs.amaranthe["the game"] = "C https://www.youtube.com/watch?v=9rVdnt5Vrno";
songs.amaranthe["crystalline"] = "C https://www.youtube.com/watch?v=pansISyvjn8";
songs.amaranthe["boomerang"] = "BC https://www.youtube.com/watch?v=Wjdm5tJ5NiA";
songs.amaranthe["on the rocks"] = "C https://www.youtube.com/watch?v=zVyyx3TRYBo";
songs.amaranthe["limitless"] = "C https://www.youtube.com/watch?v=JNvEyOCQ1f0";
songs.amaranthe["faster"] = "C https://www.youtube.com/watch?v=_n3yFsPWTEY";
songs.amaranthe["trinity"] = "C https://www.youtube.com/watch?v=T2e_3ZnJcTE";
songs.amaranthe["massive addictive"] = "C https://www.youtube.com/watch?v=xvoD98y5Dl0";
songs.amaranthe["digital world"] = "C https://www.youtube.com/watch?v=z6PYAkXO-bU";
songs.amaranthe["true"] = "C https://www.youtube.com/watch?v=8bSq4eB9cO8";
songs.amaranthe["unreal"] = "C https://www.youtube.com/watch?v=rPLhmZnG66o";
songs.amaranthe["over and done"] = "C https://www.youtube.com/watch?v=N7NtrC5gbm4";
songs.amaranthe["danger zone"] = "C https://www.youtube.com/watch?v=Iwp3m7hsbs8";
songs.amaranthe["an ordinary abnormality"] = "C https://www.youtube.com/watch?v=swD8ICx3x5k";
songs.amaranthe["that song"] = "C https://www.youtube.com/watch?v=yR05g0Co7W4";
songs.amaranthe["fury"] = "C https://www.youtube.com/watch?v=Tsbh2HgMSU0";
songs.amaranthe["break down and cry"] = "C https://www.youtube.com/watch?v=ir_o31SDhPM";
songs.amaranthe["fireball"] = "C https://www.youtube.com/watch?v=h7cIJdFhHW8";
songs.amaranthe["the score"] = "C https://www.youtube.com/watch?v=hglfL0AgGPA";
songs.amaranthe["365"]= "C https://www.youtube.com/watch?v=UDVycjDLx4Y";
songs.amaranthe["inferno"] = "C https://www.youtube.com/watch?v=VZVz7cUDZtk";
songs.amaranthe["countdown"] = "C https://www.youtube.com/watch?v=G2596YYB4Uk";
songs.amaranthe["helix"] = "C https://www.youtube.com/watch?v=GT3ZwF5qNSA";
songs.amaranthe["die and wake up"] = "C https://www.youtube.com/watch?v=GTNre1Afec0";
songs.amaranthe["do or die"] = "C https://www.youtube.com/watch?v=iZweNFWbegI";
songs.amaranthe["the catalyst"] = "C https://www.youtube.com/watch?v=5521ErpWF_M";
songs.amaranthe["insatiable"] = "C https://www.youtube.com/watch?v=5VJuiLVsFbk";
songs.amaranthe["damnation flame"] = "C https://www.youtube.com/watch?v=nbuEkMYY8uk";
songs.amaranthe["liberated"] = "C https://www.youtube.com/watch?v=va8cV8JEKko";
songs.amaranthe["revision"] = "C https://www.youtube.com/watch?v=q7lzTWtl7CI";
songs.amaranthe["interference"] = "C https://www.youtube.com/watch?v=ICgUdkLkYZ4";
songs.amaranthe["stay a little while"] = "C https://www.youtube.com/watch?v=DLaraqn3_E8";
songs.amaranthe["ecstasy"] = "C https://www.youtube.com/watch?v=N7ID2tU0qC4";
songs.amaranthe["breaking the waves"] = "C https://www.youtube.com/watch?v=3Jt4ZViBvvw";
songs.amaranthe["outer dimensions"] = "C https://www.youtube.com/watch?v=y3abhagVcgY";
songs.amaranthe["resistance"] = "C https://www.youtube.com/watch?v=vM7xZQWdyEs";
songs.amaranthe["find life"] = "C https://www.youtube.com/watch?v=9GRCY3kTi3Y";
songs.amaranthe["pvp"] = "C https://www.youtube.com/watch?v=aiX1Rc6dTJQ";
songs.amaranthe["viral"] = "C https://www.youtube.com/watch?v=-A7BPXEBh1Q";

songs.junny["bona fide"] = "BC https://www.youtube.com/watch?v=MNM_x2AqEBc";
songs.junny["levitate"] = "BC https://www.youtube.com/watch?v=8Zte8fpn12c";
songs.junny["mono"] = "BC https://www.youtube.com/watch?v=ZACnULmpVXg";
songs.junny["stay under"] = "BC https://www.youtube.com/watch?v=LVtx0TlDwnQ";
songs.junny["movie"] = "BC https://www.youtube.com/watch?v=_P9ty76m5FU";
songs.junny["menu"] = "BC https://www.youtube.com/watch?v=SusJkVuOvl4";
songs.junny["mercury"] = "C https://www.youtube.com/watch?v=rRwcspW0wp4";
songs.junny["not about you"] = "C";
songs.junny["mugshot"] = "C";
songs.junny["just a number"] = "C";
songs.junny["oh!!"] = "C";
songs.junny["obvious"] = "C";
songs.junny["color me"] = "C";
songs.junny["get ya"] = "C";
songs.junny["boyhood"] = "C";
songs.junny["rush"] = "C";
songs.junny["taste"] = "C";
songs.junny["daylight"] = "C";
songs.junny["here we go again"] = "C";
songs.junny["complications"] = "C";
songs.junny["figure8"] = "C";
songs.junny["distance"] = "C";
songs.junny["say"] = "C";
songs.junny["waste your time"] = "C";
songs.junny["trust"] = "C";
songs.junny["be mine"] = "C";
songs.junny["living dream"] = "C";
songs.junny["feel that"] = "C";
songs.junny["patience"] = "C";
songs.junny["zone"] = "C";
songs.junny["for the weekend"] = "C";
songs.junny["blind game"] = "C";
songs.junny["wywf"] = "C";
songs.junny["handle you"] = "C";
songs.junny["down under"] = "C";
songs.junny["choose"] = "C";
songs.junny["rise and fall"] = "C";
songs.junny["wine"] = "C";
songs.junny["switch"] = "C";
songs.junny["bed"] = "C";
songs.junny["success"] = "C";
songs.junny["winter"] = "C";
songs.junny["window"] = "C";
songs.junny["21"] = "C";
songs.junny["trilla"] = "C";
songs.junny["age"] = "C";
songs.junny["up all night"] = "C";
songs.junny["spoiler"] = "C";
songs.junny["years"] = "C";
songs.junny["getaway"] = "C";
songs.junny["untitled"] = "C";
songs.junny["feel"] = "C";
songs.junny["maybe"] = "C";
songs.junny["aura"] = "C";
songs.junny["by my side"] = "C";
songs.junny["new girl"] = "C";
songs.junny["sober"] = "C";
songs.junny["inside"] = "C";
songs.junny["hide and sick"] = "C";
songs.junny["darling"] = "C";
songs.junny["optimist"] = "C";
songs.junny["invitation"] = "C";

songs.jhene["brave"] = "BC https://www.youtube.com/watch?v=0paO14gvFAk";
songs.jhene["jukai"] = "BC https://www.youtube.com/watch?v=-Vowb5dcQmw";
songs.jhene["lsd"] = "BC https://www.youtube.com/watch?v=PtiXC4YLUmU";
songs.jhene["while were young"] = "BC https://www.youtube.com/watch?v=LjvwRSKVQNs";
songs.jhene["newer balance"] = "BC https://www.youtube.com/watch?v=AG3v9933ZIw";
songs.jhene["bad trip"] = "BC https://www.youtube.com/watch?v=2HYe8MtjEbI";
songs.jhene["trip"] = "BC https://www.youtube.com/watch?v=V_q8r9xt8PU";
songs.jhene["tryna smoke"] = "BC https://www.youtube.com/watch?v=-ov6tH8KSvY";
songs.jhene["born tired"] = "BC https://www.youtube.com/watch?v=kLTwNhHVc7Q";
songs.jhene["all good"] = "BC https://www.youtube.com/watch?v=8YmSeLRLYTE";
songs.jhene["mourning doves"] = "BC https://www.youtube.com/watch?v=CKxGuUkoSlU";
songs.jhene["limbo limbo limbo"] = "C https://www.youtube.com/watch?v=3UQahplNiS8";
songs.jhene["ways"] = "C https://www.youtube.com/watch?v=Sg7EqKxVSMI";
songs.jhene["to love and die"] = "C https://www.youtube.com/watch?v=EtPq5G2sKNk";
songs.jhene["spotless mind"] = "C https://www.youtube.com/watch?v=UulLW_LICOg";
songs.jhene["its cool"] = "C https://www.youtube.com/watch?v=Qn1i0VirWxg";
songs.jhene["lyin king"] = "C https://www.youtube.com/watch?v=KOhuP8Gbp2s";
songs.jhene["the pressure"] = "C https://www.youtube.com/watch?v=00bumpN0Mhw";
songs.jhene["eternal sunshine"] = "C https://www.youtube.com/watch?v=SnnJhEy9IzY";
songs.jhene["promises"] = "C https://www.youtube.com/watch?v=soQhR7uAZOY";
songs.jhene["remember"] = "C https://www.youtube.com/watch?v=DS5KmBxylJU";
songs.jhene["pretty bird"] = "C https://www.youtube.com/watch?v=UCnvRnCoGYU";
songs.jhene["blue dream"] = "C https://www.youtube.com/watch?v=9iuNkNH8J4g";
songs.jhene["beautiful ruin"] = "C https://www.youtube.com/watch?v=6Lbj8Em1M7U";
songs.jhene["moments"] = "C https://www.youtube.com/watch?v=4XlxoQoiYYg";
songs.jhene["olla"] = "C https://www.youtube.com/watch?v=HoFBrF8-Yc0";
songs.jhene["when we love"] = "C https://www.youtube.com/watch?v=ihY0NNK9wzI";
songs.jhene["sativa"] = "C https://www.youtube.com/watch?v=5x-d3pabd5o";
songs.jhene["new balance"] = "C https://www.youtube.com/watch?v=l9TDhox8vPg";
songs.jhene["you are here"] = "C https://www.youtube.com/watch?v=h5GyaW1Kzgs";
songs.jhene["never call me"] = "C https://www.youtube.com/watch?v=jnQ4V-wajLY";
songs.jhene["nobody"] = "C https://www.youtube.com/watch?v=M8F-H3M3ttw";
songs.jhene["lotus"] = "C https://www.youtube.com/watch?v=jJUXZJYmp_I";
songs.jhene["triggered"] = "C https://www.youtube.com/watch?v=t3aHdZfJckg";
songs.jhene["overstimulated"] = "C https://www.youtube.com/watch?v=tvc163EHZbE";
songs.jhene["oblivion"] = "C https://www.youtube.com/watch?v=9gi4lmcgI4k";
songs.jhene["psilocybin"] = "C https://www.youtube.com/watch?v=-BbGvFf94V4";
songs.jhene["mystic journey"] = "C https://www.youtube.com/watch?v=obv3Q7eW9Vc";
songs.jhene["picture perfect"] = "C https://www.youtube.com/watch?v=6CAfMUnpAC4";
songs.jhene["sing to me"] = "C https://www.youtube.com/watch?v=Ln31QeUseP4";
songs.jhene["frequency"] = "C https://www.youtube.com/watch?v=Qsmq9x0uVX4";
songs.jhene["ascension"] = "C https://www.youtube.com/watch?v=s6Kd2f5zykM";
songs.jhene["hello ego"] = "C https://www.youtube.com/watch?v=rEc3qrIo1Os";
songs.jhene["clear my mind"] = "C https://www.youtube.com/watch?v=NAzbvGSI0lc";
songs.jhene["none of your concern"] = "C https://www.youtube.com/watch?v=PmeRjrz8KVw";
songs.jhene["speak"] = "C https://www.youtube.com/watch?v=EUvKqjngC-w";
songs.jhene["bs"] = "C https://www.youtube.com/watch?v=tXZ_B8Amy00";
songs.jhene["pussy fairy"] = "C https://www.youtube.com/watch?v=wy2ujCUtCHU";
songs.jhene["hoe"] = "C https://www.youtube.com/watch?v=HbYLwtRpag4";
songs.jhene["one way"] = "C https://www.youtube.com/watch?v=tbs18p3sIaQ";
songs.jhene["define me"] = "C https://www.youtube.com/watch?v=A_wbndzxZTQ";
songs.jhene["surrender"] = "C https://www.youtube.com/watch?v=qwyrvolfa3I";
songs.jhene["love"] = "C https://www.youtube.com/watch?v=2iAmEMbiwVI";
songs.jhene["10k hours"] = "C https://www.youtube.com/watch?v=R--2Ty9hj-A";
songs.jhene["summer 2020"] = "C https://www.youtube.com/watch?v=fyvf9jNPTHM";
songs.jhene["pray for you"] = "C https://www.youtube.com/watch?v=mFOH6UK0Ap8";
songs.jhene["lightning and thunder"] = "C https://www.youtube.com/watch?v=Ny7GKnU0yvQ";
songs.jhene["magic hour"] = "C https://www.youtube.com/watch?v=WKQBcv10SA8";
songs.jhene["party for me"] = "C https://www.youtube.com/watch?v=SZzwO-ENXeA";
songs.jhene["a and B"] = "C https://www.youtube.com/watch?v=8vLj6PawOPg";
songs.jhene["come on"] = "C https://www.youtube.com/watch?v=yI6J8MdUqeo";
songs.jhene["on the way"] = "C https://www.youtube.com/watch?v=FhNUzYHyzJM";
songs.jhene["down again"] = "C https://www.youtube.com/watch?v=6TkNxYMCskA";
songs.jhene["wading"] = "C https://www.youtube.com/watch?v=EYS-zFrcD_A";

songs.newJeans["attention"] = "BC https://www.youtube.com/watch?v=js1CtxSY38I";
songs.newJeans["omg"] = "BC https://www.youtube.com/watch?v=sVTy_wmn5SU";
songs.newJeans["hype boy"] = "C https://www.youtube.com/watch?v=11cta61wi0g";
songs.newJeans["cookie"] = "C https://www.youtube.com/watch?v=VOmIplFAGeg";
songs.newJeans["hurt"] = "C https://www.youtube.com/watch?v=tVIXY14aJms";
songs.newJeans["new jeans"] = "C https://www.youtube.com/watch?v=G8GEpK7YDl4";
songs.newJeans["super shy"] = "C https://www.youtube.com/watch?v=ArmDp-zijuc";
songs.newJeans["eta"] = "C https://www.youtube.com/watch?v=jOTfBlKSQYY";
songs.newJeans["cool with you"] = "C https://www.youtube.com/watch?v=Wb-WCbHXnAw";
songs.newJeans["get up"] = "C https://www.youtube.com/watch?v=SXM1q0CTfew";
songs.newJeans["asap"] = "C https://www.youtube.com/watch?v=dJdqn5v4Dkw";
songs.newJeans["ditto"] = "C https://www.youtube.com/watch?v=Km71Rr9K-Bw";
songs.newJeans["how sweet"] = "C https://www.youtube.com/watch?v=Q3K0TOvTOno";
songs.newJeans["bubble gum"] = "C https://www.youtube.com/watch?v=ft70sAYrFyY";
songs.newJeans["supernatural"] = "C https://www.youtube.com/watch?v=ZncbtRo7RXs";
songs.newJeans["right now"] = "C https://www.youtube.com/watch?v=m6pTbEz4w3o";

songs.aespa["sun and moon"] = "B https://www.youtube.com/watch?v=PLsEfyfJFbo";
songs.aespa["just another girl"] = "B https://www.youtube.com/watch?v=hZP4khXrMgE";
songs.aespa["hold on tight"] = "B https://www.youtube.com/watch?v=1XZRhrt1Tkg";
songs.aespa["armageddon"] = "BC https://www.youtube.com/watch?v=nFYwcndNuOY";
songs.aespa["live my life"] = "BC https://www.youtube.com/watch?v=YEA1ROHi0Eg";
songs.aespa["prologue"] = "BC https://www.youtube.com/watch?v=P8Zd56wknlk";
songs.aespa["iconic"] = "BC https://www.youtube.com/watch?v=gj-lvvYQdiU";
songs.aespa["lucid dream"] = "BC https://www.youtube.com/watch?v=5DhAts7WcPk";
songs.aespa["aenergy"] = "C https://www.youtube.com/watch?v=BOzl6_lMfBM";
songs.aespa["better things"] = "C https://www.youtube.com/watch?v=hb73cGFLzKk";
songs.aespa["black mamba"] = "C https://www.youtube.com/watch?v=ZeerrnuLi5E";
songs.aespa["die trying"] = "C https://www.youtube.com/watch?v=u197XXtcdGg";
songs.aespa["drama"] = "C https://www.youtube.com/watch?v=D8VEhcPeSlc";
songs.aespa["dont blink"] = "C https://www.youtube.com/watch?v=bzX5R8_GqEQ";
songs.aespa["dreams come true"] = "C https://www.youtube.com/watch?v=H69tJmsgd9I";
songs.aespa["flights not feelings"] = "C https://www.youtube.com/watch?v=xBlMiqSGFps";
songs.aespa["flowers"] = "C https://www.youtube.com/watch?v=EO7s8AzviQI";
songs.aespa["forever"] = "C https://www.youtube.com/watch?v=wog1R1d4zls";
songs.aespa["get goin"] = "C https://www.youtube.com/watch?v=wPnjKZFgeiE";
songs.aespa["girls"] = "C https://www.youtube.com/watch?v=dYRITmpFbJ4";
songs.aespa["hot air balloon"] = "C https://www.youtube.com/watch?v=Rbn56x39OLs";
songs.aespa["hot mess"] = "C https://www.youtube.com/watch?v=2iK3ccCsI6s";
songs.aespa["illusion"] = "C https://www.youtube.com/watch?v=BpCvYeK5hcE";
songs.aespa["ill make you cry"] = "C https://www.youtube.com/watch?v=NBunx0VMvos";
songs.aespa["im unhappy"] = "C https://www.youtube.com/watch?v=CC7OrEx5H4U";
songs.aespa["jingle bell rock"] = "C https://www.youtube.com/watch?v=HJYetAS7cVs";
songs.aespa["kill it"] = "C https://www.youtube.com/watch?v=mJNLwrOeFOs";
songs.aespa["licorice"] = "C https://www.youtube.com/watch?v=sU0FVs9Enq8";
songs.aespa["lifes too short"] = "C https://www.youtube.com/watch?v=PLC_3ZHkNag";
songs.aespa["lingo"] = "C https://www.youtube.com/watch?v=rxtdwssXyOs";
songs.aespa["long chat"] = "C https://www.youtube.com/watch?v=USr5C0QXMVw";
songs.aespa["melody"] = "C https://www.youtube.com/watch?v=IdxYqQloU4w";
songs.aespa["mine"] = "C https://www.youtube.com/watch?v=SguQN1R1Ojs";
songs.aespa["we go"] = "C https://www.youtube.com/watch?v=P0JBkd3mJ74";
songs.aespa["next level"] = "C https://www.youtube.com/watch?v=4TWR90KJl84";
songs.aespa["pink hoodie"] = "C https://www.youtube.com/watch?v=wDWitXS0LtE";
songs.aespa["regret of the times"] = "C https://www.youtube.com/watch?v=nPEDHaPVSRk";
songs.aespa["salty and sweet"] = "C https://www.youtube.com/watch?v=Mt-Za8YUnt8";
songs.aespa["savage"] = "C https://www.youtube.com/watch?v=WPdWvnAAurg";
songs.aespa["set the tone"] = "C https://www.youtube.com/watch?v=8_4Debx0YlQ";
songs.aespa["spicy"] = "C https://www.youtube.com/watch?v=Os_heh8vPfs";
songs.aespa["supernova"] = "C https://www.youtube.com/watch?v=phuiiNCxRMg";
songs.aespa["til we meet again"] = "C https://www.youtube.com/watch?v=QeTNjrmsUwc";
songs.aespa["thirsty"] = "C https://www.youtube.com/watch?v=i0RCcSBPjuU";
songs.aespa["trick or trick"] = "C https://www.youtube.com/watch?v=AvzoFZsShKg";
songs.aespa["welcome to my world"] = "C https://www.youtube.com/watch?v=0xdB_vo4r2c";
songs.aespa["bahama"] = "C https://www.youtube.com/watch?v=44NE7bVKAYc";
songs.aespa["whiplash"] = "C https://www.youtube.com/watch?v=jWQx2f-CErU";
songs.aespa["yeppi yeppi"] = "C https://www.youtube.com/watch?v=syYqQoE5Rbo";
songs.aespa["yolo"] = "C https://www.youtube.com/watch?v=SsW6Jkf4jQQ";
songs.aespa["you"] = "C https://www.youtube.com/watch?v=sYwQdtW5x3U";
songs.aespa["zoom zoom"] = "C https://www.youtube.com/watch?v=YSEwEFuMPPM";
songs.aespa["ICU"] = "C https://www.youtube.com/watch?v=aGV_8CYCN3g";

songs.rose["call it the end"] = "A https://www.youtube.com/watch?v=nOo3a2tT1LQ";
songs.rose["too bad for us"] = "AB https://www.youtube.com/watch?v=FQmgNCStzQM";
songs.rose["drinks or coffee"] = "B https://www.youtube.com/watch?v=PFDO5OZO61Y";
songs.rose["two years"] = "B https://www.youtube.com/watch?v=lktucPDH5IY";
songs.rose["number one girl"] = "B https://www.youtube.com/watch?v=pZ1NdE69VTs";
songs.rose["stay a little longer"] = "BC https://www.youtube.com/watch?v=vHvOYQ0hbBA";
songs.rose["toxic till the end"] = "BC https://www.youtube.com/watch?v=eA0lHNZ1KCA";
songs.rose["3am"] = "C https://www.youtube.com/watch?v=OzdJFXyO8ts";
songs.rose["dance all night"] = "C https://www.youtube.com/watch?v=h7HP9aiIFfc";
songs.rose["gameboy"] = "C https://www.youtube.com/watch?v=JwKOLJl5oRM";
songs.rose["not the same"] = "C https://www.youtube.com/watch?v=IKqVcaVrMGs";
songs.rose["APT"] = "C https://www.youtube.com/watch?v=ekr2nIex040";


songs.stayc["ill be there"] = "A https://www.youtube.com/watch?v=OD2k86rKRI4";
songs.stayc["so bad"] = "AB https://www.youtube.com/watch?v=lcRV2gyEfMo";
songs.stayc["meow"] = "AB https://www.youtube.com/watch?v=b8yjHGQ4hA4";
songs.stayc["beautiful monster"] = "B https://www.youtube.com/watch?v=juQvizeZJFM";
songs.stayc["young luv"] = "BC https://www.youtube.com/watch?v=J8VHA8HeK4Q";
songs.stayc["gummy bear"] = "BC https://www.youtube.com/watch?v=yyFyEsdRlEY";
songs.stayc["meant to be"] = "BC https://www.youtube.com/watch?v=Zszb7LQ3T6Q";
songs.stayc["twenty"] = "C https://www.youtube.com/watch?v=1P3k6gaSrPY";
songs.stayc["give it 2 me"] = "C https://www.youtube.com/watch?v=-DGK4SmCN38";
songs.stayc["let me know"] = "C https://www.youtube.com/watch?v=R9tSNI-F9Xo";
songs.stayc["roses"] = "C https://www.youtube.com/watch?v=-J1StxqwgXk";
songs.stayc["beauty bomb"] = "C https://www.youtube.com/watch?v=7_bHnNjVbuM";
songs.stayc["stay with me"] = "C https://www.youtube.com/watch?v=2RMarP7itak";
songs.stayc["flexing on my ex"] = "C https://www.youtube.com/watch?v=Q-jBR3Sj61Y";
songs.stayc["slow down"] = "C https://www.youtube.com/watch?v=0IEha20W_sM";
songs.stayc["complex"] = "C https://www.youtube.com/watch?v=PIK0WuoWGMU";
songs.stayc["247"] = "C https://www.youtube.com/watch?v=gzuquPJ7ieE";
songs.stayc["cheeky icy thang"] = "C https://www.youtube.com/watch?v=s-UXxaQdUew";
songs.stayc["1 thing"] = "C https://www.youtube.com/watch?v=_GhDDSjmNww";
songs.stayc["find"] = "C https://www.youtube.com/watch?v=hdErWXlOmYw";
songs.stayc["nada"] = "C https://www.youtube.com/watch?v=o2msjOsmlYA";
songs.stayc["troublemaker"] = "C https://www.youtube.com/results?search_query=stayc+troublemaker";
songs.stayc["stereotype"] = "C https://www.youtube.com/watch?v=Xmxcnf2v_gs";
songs.stayc["run2u"] = "C https://www.youtube.com/watch?v=grG41kS4MUA";
songs.stayc["same same"] = "C https://www.youtube.com/watch?v=baZRXY30HU4";
songs.stayc["not like you"] = "C https://www.youtube.com/watch?v=lHoqyw5QxT0";
songs.stayc["be mine"] = "C https://www.youtube.com/watch?v=7JYXOYifvfI";
songs.stayc["butterfly"] = "C https://www.youtube.com/watch?v=3zIX_GrFVBc";
songs.stayc["i want u baby"] = "C https://www.youtube.com/watch?v=VZdrbWKMtKc";
songs.stayc["bubble"] = "C https://www.youtube.com/watch?v=3-ptVHZZdBg";
songs.stayc["i wanna do"] = "C https://www.youtube.com/watch?v=ms10oDKzsuc";
songs.stayc["asap"] = "BC https://www.youtube.com/watch?v=NsY-9MCOIAQ";
songs.stayc["so what"] = "C https://www.youtube.com/watch?v=_uyNlm8RUIc";
songs.stayc["i like it"] = "C https://www.youtube.com/watch?v=KsxRanyHS7o";
songs.stayc["run2utak"] = "C https://www.youtube.com/watch?v=grG41kS4MUA";
songs.stayc["teddy bear"] = "C https://www.youtube.com/watch?v=SxHmoifp0oQ";
songs.stayc["like this"] = "C https://www.youtube.com/watch?v=RXEwodJ6pH4";
songs.stayc["love fool"] = "C https://www.youtube.com/watch?v=Dr-S7RWeh5I";
songs.stayc["love"] = "C https://www.youtube.com/watch?v=xDzKCr58jJA";
songs.stayc["poppy"] = "C https://www.youtube.com/watch?v=YkZvwVf7F9k";
songs.stayc["lit"] = "C https://www.youtube.com/watch?v=hB6B70NyZ7s";
songs.stayc["star"] = "C https://www.youtube.com/watch?v=MvctsSSLSk0";
songs.stayc["tell me now"] = "C https://www.youtube.com/watch?v=iNkpqr7G6h4";
songs.stayc["fakin"] = "C https://www.youtube.com/watch?v=FF2QwRyM-u0";
songs.stayc["gpt"] = "C https://www.youtube.com/watch?v=DskqpUrvlmw";

songs.taeyeon["siren"] = "AB https://www.youtube.com/watch?v=kci45V8zPx8";
songs.taeyeon["cant control myself"] = "AB https://www.youtube.com/watch?v=RccDIpx4ZMM";
songs.taeyeon["toddler"] = "AB https://www.youtube.com/watch?v=EaIb4RzAvEI";
songs.taeyeon["no love again"] = "B https://www.youtube.com/watch?v=XaPZKYbmveQ";
songs.taeyeon["spark"] = "B https://www.youtube.com/watch?v=eP4ga_fNm-E";
songs.taeyeon["burn it down"] = "B https://www.youtube.com/watch?v=Bexk2HA3J-Y";
songs.taeyeon["some nights"] = "B https://www.youtube.com/watch?v=a7NoogZ2eFo";
songs.taeyeon["dear me"] = "B https://www.youtube.com/watch?v=bho0m505qVA";
songs.taeyeon["ending credits"] = "BC https://www.youtube.com/watch?v=DCtcLIS3yhw";
songs.taeyeon["you better not"] = "B https://www.youtube.com/watch?v=t-0-i5vmtBo";
songs.taeyeon["stress"] = "BC https://www.youtube.com/watch?v=N2NLxGkr8kg";
songs.taeyeon["do you love me"] = "BC https://www.youtube.com/watch?v=d6CkeV4Hves";
songs.taeyeon["my tragedy"] = "BC https://www.youtube.com/watch?v=M02W--fl1js";
songs.taeyeon["here i am"] = "BC https://www.youtube.com/watch?v=q_rQmUVgCo0";
songs.taeyeon["find me"] = "BC https://www.youtube.com/watch?v=WU7SsAnDLKw";
songs.taeyeon["INVU"] = "C https://www.youtube.com/watch?v=AbZH7XWDW_k";
songs.taeyeon["all for nothing"] = "C https://www.youtube.com/watch?v=jXOQ9LG83uw";
songs.taeyeon["fabulous"] = "C https://www.youtube.com/watch?v=705BcZyCfzk";
songs.taeyeon["what do i call you"] = "C https://www.youtube.com/watch?v=5LbFdY6vGsQ";
songs.taeyeon["heaven"] = "C https://www.youtube.com/watch?v=oE8hAQie8fw";
songs.taeyeon["LOL"] = "C https://www.youtube.com/watch?v=6WSGQePUCG8";
songs.taeyeon["to x"] = "C https://www.youtube.com/watch?v=5_n6t9G2TUQ";
songs.taeyeon["blue"] = "C https://www.youtube.com/watch?v=tVtTdZt-HtI";
songs.taeyeon["baram x 3"] = "C https://www.youtube.com/watch?v=jIMlOeX7xZ4";
songs.taeyeon["circus"] = "C https://www.youtube.com/watch?v=mATYset8O_w";
songs.taeyeon["blue eyes"] = "C https://www.youtube.com/watch?v=9D6XKwSUvqM";
songs.taeyeon["strangers"] = "C https://www.youtube.com/watch?v=C-g3og829ds";
songs.taeyeon["playlist"] = "C https://www.youtube.com/watch?v=qR12qLydc2Y";
songs.taeyeon["wildfire"] = "C https://www.youtube.com/watch?v=EDld1mE9iMk";
songs.taeyeon["better babe"] = "C https://www.youtube.com/watch?v=914tZ2WA89g";
songs.taeyeon["disaster"] = "C https://www.youtube.com/watch?v=GE8wQuR0Frg";
songs.taeyeon["cover up"] = "C https://www.youtube.com/watch?v=8UrO8_nH_rA";
songs.taeyeon["feel so fine"] = "C https://www.youtube.com/watch?v=YIrON_YUE70";
songs.taeyeon["im ok"] = "C https://www.youtube.com/watch?v=9zvomniEtyU";
songs.taeyeon["sweet love"] = "C https://www.youtube.com/watch?v=BwSfIPrQBtY";
songs.taeyeon["lonely night"] = "C https://www.youtube.com/watch?v=Eyesx3q0G-Q";
songs.taeyeon["eraser"] = "C https://www.youtube.com/watch?v=ANGrtJ4rPQM";
songs.taeyeon["curtain call"] = "C https://www.youtube.com/watch?v=2ls0hrgS6pc";
songs.taeyeon["11:11"] = "C https://www.youtube.com/watch?v=ulr0muQKjk0";
songs.taeyeon["i"] = "C https://www.youtube.com/watch?v=4OrCA1OInoo";
songs.taeyeon["blur"] = "C https://www.youtube.com/watch?v=ov3-8gKI80g";
songs.taeyeon["why"] = "C https://www.youtube.com/watch?v=WkdtmT8A2iY";
songs.taeyeon["timeless"] = "C https://www.youtube.com/watch?v=nXhrixCxfmc";
songs.taeyeon["gemini"] = "C https://www.youtube.com/watch?v=utQnBezl8xk";
songs.taeyeon["farewell"] = "C https://www.youtube.com/watch?v=U4PE_Xu4xI4";
songs.taeyeon["fine"] = "C https://www.youtube.com/watch?v=NHXUM-6a3dU";
songs.taeyeon["time lapse"] = "C https://www.youtube.com/watch?v=qDW-sVVtTGk";
songs.taeyeon["set myself on fire"] = "C https://www.youtube.com/watch?v=U03r-YzpOjg";
songs.taeyeon["hot mess"] = "C https://www.youtube.com/watch?v=GFq4sJFv4_k";
songs.taeyeon["four seasons"] = "C https://www.youtube.com/watch?v=4HG_CJzyX6A";
songs.taeyeon["U R"] = "C https://www.youtube.com/watch?v=woqRmrtVhgM";
songs.taeyeon["letter to myself"] = "C https://www.youtube.com/watch?v=wqN1vLPX-no";
songs.taeyeon["starlight"] = "C https://www.youtube.com/watch?v=eNmL4JiGxZQ";
songs.taeyeon["good thing"] = "C https://www.youtube.com/watch?v=V1HpJ_GdwoQ";
songs.taeyeon["rain"] = "C https://www.youtube.com/watch?v=eHir_vB1RUI";
songs.taeyeon["make me love you"] = "C https://www.youtube.com/watch?v=TVUqLBRQom8";
songs.taeyeon["time spent walking through memories"] = "C https://www.youtube.com/watch?v=w5Ckk2zDDsc";
songs.taeyeon["weekend"] = "C https://www.youtube.com/watch?v=RmuL-BPFi2Q";
songs.taeyeon["cold as hell"] = "C https://www.youtube.com/watch?v=Hgff4l844hs";
songs.taeyeon["happy"] = "C https://www.youtube.com/watch?v=Raj-AuQgCTg";
songs.taeyeon["fashion"] = "C https://www.youtube.com/watch?v=s6mO2Esa1Fc";
songs.taeyeon["wine"] = "C https://www.youtube.com/watch?v=IbOBBK3kVss";
songs.taeyeon["nightmare"] = "C https://www.youtube.com/watch?v=zM8txXJSpQs";
songs.taeyeon["melt away"] = "C https://www.youtube.com/watch?v=PrBnp5_hFMM";
songs.taeyeon["heart"] = "C https://www.youtube.com/watch?v=xA3-NV2tZhM";
songs.taeyeon["drawing our moments"] = "C https://www.youtube.com/watch?v=iDuBodFlFnc";
songs.taeyeon["something new"] = "C https://www.youtube.com/watch?v=im1UUY8dQIk";
songs.taeyeon["all night long"] = "C https://www.youtube.com/watch?v=IonCCgA_BZE";
songs.taeyeon["one day"] = "C https://www.youtube.com/watch?v=y9GUYCCJf-s";
songs.taeyeon["i got love"] = "C https://www.youtube.com/watch?v=MHqy1JsVvIE";
songs.taeyeon["when i was young"] = "C https://www.youtube.com/watch?v=MbN11BPmKlI";
songs.taeyeon["one day"] = "C https://www.youtube.com/watch?v=y9GUYCCJf-s";
songs.taeyeon["i got love"] = "C https://www.youtube.com/watch?v=MHqy1JsVvIE";
songs.taeyeon["when i was young"] = "C https://www.youtube.com/watch?v=MbN11BPmKlI";
songs.taeyeon["i blame on you"] = "C https://www.youtube.com/watch?v=0dFyxUAgtu4";
songs.taeyeon["love in color"] = "C https://www.youtube.com/watch?v=B1lSlKXjoR8";
songs.taeyeon["hands on me"] = "C https://www.youtube.com/watch?v=OFV7xzABSOA";
songs.taeyeon["night"] = "C https://www.youtube.com/watch?v=gFm7EbQN73w";
songs.taeyeon["city love"] = "C https://www.youtube.com/watch?v=pzgK4cxZ_94";
songs.taeyeon["love you like crazy"] = "C https://www.youtube.com/watch?v=1JeAWRL1ACc";
songs.taeyeon["gravity"] = "C https://www.youtube.com/watch?v=0hNde677fAE";

songs.ghost["absolution"] = "C https://www.youtube.com/watch?v=gyrto4U884o";
songs.ghost["ashes"] = "BC https://www.youtube.com/watch?v=FxK3C7pXX4U";
songs.ghost["avalanche"] = "BC https://www.youtube.com/watch?v=dCKachhUqn4";
songs.ghost["bible"] = "BC https://www.youtube.com/watch?v=887lax8LDDg";
songs.ghost["bite of passage"] = "C https://www.youtube.com/watch?v=C2pLkzpevao";
songs.ghost["body and blood"] = "C https://www.youtube.com/watch?v=S0UgjyL4d1g";
songs.ghost["call me little sunshine"] = "BC https://www.youtube.com/watch?v=DD2m_iqD7dI";
songs.ghost["cirice"] = "C https://www.youtube.com/watch?v=-0Ao4t_fe0I";
songs.ghost["con clavi con dio"] = "C https://www.youtube.com/watch?v=nhuO03S4KmM";
songs.ghost["crucified"] = "B https://www.youtube.com/watch?v=G01Hb-WM2Uw";
songs.ghost["dance macabre"] = "C https://www.youtube.com/watch?v=7Gr63DiEUxw";
songs.ghost["darkness at the heart of my love"] = "B https://www.youtube.com/watch?v=tzXFZuB1wSQ";
songs.ghost["death knell"] = "BC https://www.youtube.com/watch?v=qJy-hdKT5wM";
songs.ghost["depth of satans eyes"] = "C https://www.youtube.com/watch?v=-EHYnB_-z48";
songs.ghost["deus culpa"] = "B https://www.youtube.com/watch?v=-vHe7MDTurQ";
songs.ghost["deus in absentia"] = "C https://www.youtube.com/watch?v=Bp6EK84gnrI";
songs.ghost["devil church"] = "BC https://www.youtube.com/watch?v=rZdG1dUFtx0";
songs.ghost["dominion"] = "BC https://www.youtube.com/watch?v=N1U7buIoHqc";
songs.ghost["elizabeth"] = "BC https://www.youtube.com/watch?v=quyhwEH4dlo";
songs.ghost["enter sandman"] = "C https://www.youtube.com/watch?v=BTA6zBU0-4k";
songs.ghost["faith"] = "C https://www.youtube.com/watch?v=k72ytAFMCI0";
songs.ghost["the future is a foreign land"] = "C https://www.youtube.com/watch?v=lz24W6CQ0HI";
songs.ghost["from the pinnacle to the pit"] = "C https://www.youtube.com/watch?v=6A-IoOEPbUs";
songs.ghost["genesis"] = "BC https://www.youtube.com/watch?v=4FwwZMaHsDs";
songs.ghost["ghuleh zombie queen"] = "BC https://www.youtube.com/watch?v=yRB1hTjxjMg";
songs.ghost["griftwood"] = "BC https://www.youtube.com/watch?v=d6WA06fNscc";
songs.ghost["hanging around"] = "C https://www.youtube.com/watch?v=0Rn3I08crPo";
songs.ghost["he is"] = "BC https://www.youtube.com/watch?v=7hMaHDTw-pI";
songs.ghost["helvetesfonster"] = "BC https://www.youtube.com/watch?v=tP_Tz35iob4";
songs.ghost["here comes the sun"] = "C https://www.youtube.com/watch?v=gd4QLcJj-3U";
songs.ghost["hunters moon"] = "C https://www.youtube.com/watch?v=rtkaUZvMaG8";
songs.ghost["i believe"] = "C https://www.youtube.com/watch?v=VVM0dqhyaqQ";
songs.ghost["idolatrine"] = "C https://www.youtube.com/watch?v=c-YlHaT5WFQ";
songs.ghost["if you have ghosts"] = "C https://www.youtube.com/watch?v=4kNetd_lISI";
songs.ghost["im a marionette"] = "C https://www.youtube.com/watch?v=-vyT6zvSNps";
songs.ghost["imperium"] = "B https://www.youtube.com/watch?v=iuYxW_RiSaw";
songs.ghost["infestissumam"] = "C https://www.youtube.com/watch?v=a5mAxXU9-yU";
songs.ghost["its a sin"] = "C https://www.youtube.com/watch?v=4t-g615PEtg";
songs.ghost["jesus he knows me"] = "BC https://www.youtube.com/watch?v=GBiKayMXLk0";
songs.ghost["jigolo har megiddo"] = "AB https://www.youtube.com/watch?v=WKxkj4OaAq4";
songs.ghost["kiss the go-goat"] = "C https://www.youtube.com/watch?v=Db86lpidcz4";
songs.ghost["la mantra mori"] = "C https://www.youtube.com/watch?v=3dMnKQnEDLE";
songs.ghost["life eternal"] = "C https://www.youtube.com/watch?v=xUSf1bjd4I8";
songs.ghost["mary on a cross"] = "C https://www.youtube.com/watch?v=k5mX3NkA7jM";
songs.ghost["majesty"] = "C https://www.youtube.com/watch?v=qS5-QmkKzJQ";
songs.ghost["miasma"] = "BC https://www.youtube.com/watch?v=5CWWukDu8qQ";
songs.ghost["missionary man"] = "C https://www.youtube.com/watch?v=I9zfPSpwPeg";
songs.ghost["mummy dust"] = "C https://www.youtube.com/watch?v=34QRJnSg17Y";
songs.ghost["monstrance clock"] = "BC https://www.youtube.com/watch?v=6oa_nbgE8M8";
songs.ghost["nocturnal me"] = "B https://www.youtube.com/watch?v=mTdaLHyXIAk";
songs.ghost["per aspera ad inferni"] = "C https://www.youtube.com/watch?v=g4_IK4z9y0c";
songs.ghost["phantom of the opera"] = "C https://www.youtube.com/watch?v=Wn-VdZ4LEKg";
songs.ghost["prime mover"] = "C https://www.youtube.com/watch?v=hRkpgndVw8Y";
songs.ghost["pro memoria"] = "BC https://www.youtube.com/watch?v=leUKmlDGHiI";
songs.ghost["rats"] = "BC https://www.youtube.com/watch?v=C_ijc7A5oAc";
songs.ghost["respite on the spitalfields"] = "BC https://www.youtube.com/watch?v=JA21qOo2mWs";
songs.ghost["ritual"] = "C https://www.youtube.com/watch?v=0PakoE1eBps";
songs.ghost["satan prayer"] = "C https://www.youtube.com/watch?v=vjW4W9YsxZI";
songs.ghost["secular haze"] = "C https://www.youtube.com/watch?v=vyQZ13jobIY";
songs.ghost["see no evil"] = "C https://www.youtube.com/watch?v=pExnH7HVHtw";
songs.ghost["see the light"] = "C https://www.youtube.com/watch?v=YNOLfVAv_28";
songs.ghost["spillways"] = "C https://www.youtube.com/watch?v=u9DV1eHQpcA";
songs.ghost["spirit"] = "C https://www.youtube.com/watch?v=0GCfdelx3yE";
songs.ghost["spoksonat"] = "BC https://www.youtube.com/watch?v=N14I8YJqwVg";
songs.ghost["square hammer"] = "C https://www.youtube.com/watch?v=VqoyKzgkqR4";
songs.ghost["stand by him"] = "C https://www.youtube.com/watch?v=J_uKtPdlfvA";
songs.ghost["stay"] = "BC https://www.youtube.com/watch?v=agXKgOxKgMU";
songs.ghost["twenties"] = "C https://www.youtube.com/watch?v=nQ-pxlKgiTI";
songs.ghost["waiting for the night"] = "B https://www.youtube.com/watch?v=61KyIYpFBEc";
songs.ghost["watcher in the sky"] = "C https://www.youtube.com/watch?v=0mGr5bMItQY";
songs.ghost["we dont need another hero"] = "C https://www.youtube.com/watch?v=AMsV7qigmgQ";
songs.ghost["witch image"] = "C https://www.youtube.com/watch?v=tMwmEcKVgtM";
songs.ghost["year zero"] = "C https://www.youtube.com/watch?v=gkBt7yLXyDk";
songs.ghost["zenith"] = "B https://www.youtube.com/watch?v=-9d7ijai2Zg";

songs.aespa["rats"] = "C";

var artists = ['amaranthe','junny','jhene','newJeans', 'aespa', 'rose', 'stayc', 'taeyeon', 'ghost'];
var scores = new Array(artists.length).fill(0)
for (var i = 0; i<artists.length; i++) {
  var quotient = 0;
  for (const [key, value] of Object.entries(songs[artists[i]])) {
    quotient+=1;
    
    if (value.startsWith('AB')) {
      scores[i] += 4;
    }
    else if (value.startsWith('BC')) {
      scores[i] += 1;
    }
    else if (value.startsWith('A')) {
      scores[i] += 8;
    }
    else if (value.startsWith('B')) {
      scores[i] += 2;
    } 
  }
  scores[i] = scores[i]/quotient;
}

const keys = Array.from(scores.keys()).sort((a, b) => scores[b] - scores[a])

const sortedScores = keys.map(i => scores[i]),
      sortedArtists = keys.map(i => artists[i])

for (var i = 0; i<sortedScores.length; i++) {
  $('select').innerHTML += '<small id="' + sortedArtists[i] + '" class="artists" onclick = toggleArtist()>'+ parseInt(sortedScores[i]*10) + ' ' + sortedArtists[i] + '</small><br>'
}

//for %i in (*.opus) do ffmpeg -i "%i" "%~ni.m4a"

